version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8eupftz8ihgd"
s3_prefix = "crud"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
